<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-10-15 12:56

$extensionPath = t3lib_extMgm::extPath('t3registration_test');
return array(
	'tx_t3registrationtest_hooks' => $extensionPath . 'hooks/class.tx_t3registrationtest_hooks.php',
	'tx_t3registrationtest_mail' => $extensionPath . 'library/class.tx_t3registrationtest_mail.php',
    'tx_t3registrationtest_http' => $extensionPath . 'library/class.tx_t3registrationtest_http.php',
	'tx_t3registrationtest_tca' => $extensionPath . 'library/class.tx_t3registrationtest_tca.php',
);
?>